### PR TITLE
fix(plugin-search): generate data on demand

### LINKED ISSUE #487: renderPageContent only works in production
## Bug report

`api.renderer.renderPageContent` only works in production mode.

#### Steps to reproduce

Create a project with `saber-plugin-search` with the `index` option including `content`.

#### What is expected?

`content` should be set properly, as it is in production mode.

#### What is actually happening?

https://github.com/saberland/saber/blob/781995529eb66eb219af344e13feb039662aa1f5/packages/saber-plugin-search/lib/index.js#L47-L49

`renderPageContent` throws an error.

```
[error] TypeError: Cannot read property 'renderToString' of undefined
    at VueRenderer.renderPageContent (~/node_modules/saber/vue-renderer/lib/index.js:292:38)
    at Promise.all.map (~/node_modules/saber/packages/saber-plugin-search/lib/index.js:48:36)
    at Array.map (<anonymous>)
    at generateLocale (~/node_modules/saber/packages/saber-plugin-search/lib/index.js:31:31)
    at Promise.all.allLocalePaths.map.localePath (~/node_modules/saber/packages/saber-plugin-search/lib/index.js:67:40)
    at Array.map (<anonymous>)
    at generateDatabase (~/node_modules/saber/packages/saber-plugin-search/lib/index.js:67:22)
    at api.hooks.onCreatePages.tapPromise (~/node_modules/saber/packages/saber-plugin-search/lib/index.js:83:18)
    at tapInfo.fn.args (~/node_modules/saber/lib/index.js:88:20)
    at Promise (eval at create (~/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:46:17)
error Command failed with exit code 1.
```

#### Other relevant information

- Result of running `saber -v`: latest
- Browser version (optional): 
- Is Saber a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled?

### PR DESCRIPTION
**Pull request by egoist**
**Summary**

Fixed #487 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

---

cc/ @krmax44

### CODE REVIEW

File: packages/saber-plugin-search/lib/index.js [hunk 1]
```diff
@@ -79,18 +79,19 @@ exports.apply = (api, options) => {
...
+    // api.hooks.onCreateRenderer.tapPromise(ID, async () => {
+    //   db = await generateDatabase()
+    // })
 
     api.hooks.onCreateServer.tap(ID, server => {
-      server.get('/_saber/plugin-search/:locale.json', (req, res) => {
-        const db = getLocale(req.params.locale)
-        if (db) {
+      server.get('/_saber/plugin-search/:locale.json', async (req, res) => {
+        db = await generateDatabase()
```
Comment (egoist) [inline packages/saber-plugin-search/lib/index.js]: maybe we can generate db when it's actually used, wdyt? 😄 @krmax44

Comment (krmax44) [reply packages/saber-plugin-search/lib/index.js]: Yup, that seems to work!
