### PR TITLE
fix: publicUrl behaviour #261

### LINKED ISSUE #261: `publicUrl` doesn't behave as expected.
[Issuehunt badges](https://issuehunt.io/r/saberland/saber/issues/261)

- [x] I confirm that this is an issue rather than a question.

## Bug report

Setting `build.publicUrl` seems to correctly change the expected path for importing out of `_saber`, but the generated site still thinks that 'home' is `/` not `/publicURL/`.

I'm attempting to use saber to generate internal documentation on a self-hosted gitlab instance, using GitlabPages. Our pages urls are in the form of `https://group-name.pages.git.example.com/project-name/`. Setting `publicUrl` to `/project-name/`, while the site technically works, means that going to the index page takes me to the 404, and I have to hit 'back to home' to get the index, which has changed the url to be `https://group-name.git.example.com/`.

#### Version

`v0.6.7`

#### Steps to reproduce

You can see an illustration of this here:
https://morgul.gitlab.io/saber-publicurl-bug/

All that was required to reproduce it, however was:

1. Start a basic saber project.
2. Set `publicUrl`
3. Serve on a location other than `/`

_Note: When I didn't have a theme set, I got a weird combination of the 404 page with some of the index page's content mixed in. Setting a theme just gets me just the normal 404 page._

#### What is expected?

I would expect to see the site.

#### What is actually happening?

I get the 404 page, and the 'Back' button takes me to the site correctly, but the URL is wrong, and refreshing the page, of course, generates a 404.

#### Other relevant information

- Result of running `saber -v`:
  - saber/0.6.7 darwin-x64 node-v12.4.0
- Browser version (optional):
  - Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Is Saber a global or local install?
  - local
- Which package manager did you use for the install?
  - `yarn`
- Does this issue occur when all plugins are disabled?
  - yes

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $60.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by krmax44**
**Summary**

Fixes #261 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Published PR with canary version: <details><summary>Canary Versions</summary>
 - `extract-sfc-blocks@0.0.3-canary.263.9c0f718.0`
 - `create-blog@0.2.7-canary.263.9c0f718.0`
 - `create-site@0.3.1-canary.263.9c0f718.0`
 - `saber-highlight-css@0.0.6-canary.263.9c0f718.0`
 - `saber-highlighter-prism@0.3.2-canary.263.9c0f718.0`
 - `saber-log@0.2.1-canary.263.9c0f718.0`
 - `saber-markdown@0.0.8-canary.263.9c0f718.0`
 - `saber-plugin-feed@0.3.3-canary.263.9c0f718.0`
 - `saber-plugin-git-modification-time@0.0.4-canary.263.9c0f718.0`
 - `saber-plugin-google-analytics@0.0.7-canary.263.9c0f718.0`
 - `saber-plugin-image@0.0.5-canary.263.9c0f718.0`
 - `saber-plugin-meta-redirect@0.0.6-canary.263.9c0f718.0`
 - `saber-plugin-netlify-redirect@0.0.7-canary.263.9c0f718.0`
 - `saber-plugin-prismjs@0.2.2-canary.263.9c0f718.0`
 - `saber-plugin-pwa@0.3.4-canary.263.9c0f718.0`
 - `saber-plugin-query-posts@0.3.3-canary.263.9c0f718.0`
 - `saber-plugin-transformer-html@0.0.6-canary.263.9c0f718.0`
 - `saber-plugin-transformer-pug@0.0.6-canary.263.9c0f718.0`
 - `saber-utils@0.1.5-canary.263.9c0f718.0`
 - `saber@0.6.8-canary.263.9c0f718.0`</details>

### CODE REVIEW

**Comment by krmax44** [comment]
@Morgul Would you mind testing again with my patch? Should be working now :)

File: packages/saber/lib/utils/validateConfig.js [hunk 1]
```diff
@@ -103,8 +103,10 @@ module.exports = (config, { dev }) => {
     // Always use  / in dev mode
     result.build.publicUrl = '/'
   } else {
-    // Ensure that build.publicUrl ends with slash
-    result.build.publicUrl = result.build.publicUrl.replace(/\/?$/, '/')
+    // Ensure that build.publicUrl ends and starts with slash
+    result.build.publicUrl = result.build.publicUrl
+      .replace(/^\/?/, '/') // starting slash
```
Comment (egoist) [inline packages/saber/lib/utils/validateConfig.js]: publicUrl can be full url, i.e. starting with `http`

File: packages/saber/vue-renderer/app/router.js [hunk 2]
```diff
@@ -35,6 +36,7 @@ export default () => {
     new Router({
       mode: 'history',
       routes,
+      base: publicUrl,
```
Comment (egoist) [inline packages/saber/vue-renderer/app/router.js]: only needed in production?

Comment (krmax44) [reply packages/saber/vue-renderer/app/router.js]: That's a non-issue, as `validateConfig` already takes care of that:

https://github.com/saberland/saber/blob/98ae9198ea210630a517e4945216df743f2ceb5a/packages/saber/lib/utils/validateConfig.js#L102-L105

File: packages/saber/lib/utils/validateConfig.js (hunk 1 above)
Comment (krmax44) [reply packages/saber/lib/utils/validateConfig.js]: Hmm, we need to avoid values like `mypath/` though, as those cause assets not to load properly. Maybe check if it starts with `https?://` and then decide whether or not to prepend a `/`?

Comment (egoist) [reply packages/saber/lib/utils/validateConfig.js]: a statement should be fine.

File: packages/saber/vue-renderer/app/router.js (hunk 2 above)
Comment (egoist) [inline packages/saber/vue-renderer/app/router.js]: if i remember correctly, `base` can only be a pathname?

Comment (krmax44) [reply packages/saber/vue-renderer/app/router.js]: I tried it with an URI and that worked

**Comment by Morgul** [comment]
@krmax44 Took me a bit to reproduce it locally, but I was able to, and then I pulled down your branch, and everything seem to be working correctly!

I'm not sure the best way to get an installable version of saber so I can try it inside of GitLab, but I'm confident enough in my local test.

File: packages/saber/vue-renderer/app/router.js [hunk 3]
```diff
@@ -2,6 +2,7 @@ import Vue from 'vue'
 import Router from './vendor/vue-router'
 import RoutePrefetch from './vendor/vue-router-prefetch'
 import routes from '#cache/routes'
+import { publicUrl } from 'saber/config'
```
Comment (egoist) [inline packages/saber/vue-renderer/app/router.js]: it's actually already available as `__PUBLIC_URL__`

**Comment by egoist** [comment]
I think the routes we used to generate static HTML files need to be prefixed as well? i.e. it should be `['/blog', '/blog/about']` instead of `['/', '/about']` if you set `publicUrl` to `/blog`.
