### PR TITLE
fix: frontmatter asset loading, fixes #169

### LINKED ISSUE #169: bug: Frontmatter asset loading not working with injectAllPosts
- [x] I confirm that this is an issue rather than a question.

## Bug report

Webpack frontmatter asset loading fails with `saber-plugin-query-posts`.

#### Version

0.5.4, latest git master

#### Steps to reproduce

Create a post with at least one frontmatter asset and an `index.md` with `injectAllPosts` set to `true`. The build for the index page will fail, as the asset is imported relative to its post, rather than relative to the Saber project root or absolute.

#### What is expected?

Correct asset loading, even for pages with `injectAllPosts` set to `true`.

#### What is actually happening?

The asset can only be correctly required for pages/posts within the same path as the parent post, that is the post where the asset is required.

#### Other relevant information

- Result of running `saber -v`: 0.5.4
- Browser version (optional): Firefox/Chrome latest
- Is Saber a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled? no, of course not :wink: 

See my initial approach to frontmatter asset loading, it includes the path to the asset:

https://github.com/krmax44/saber/blob/57190a34580c60de2175c4d2a6158770ba565e62/packages/saber/vue-renderer/lib/page-prop-loader.js#L33-L40

### PR DESCRIPTION
**Pull request by krmax44**
**Summary**

See #169

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: packages/saber/lib/utils/assetsAttribute.js [hunk 1]
```diff
@@ -12,15 +14,16 @@ const MARK_GLOBAL_RE = new RegExp(`"${MARK}([^"]+)"`, 'g')
 
 /**
  * Prefix MARK to asset path
- * @param {{[key: string]: string}} assets
+ * @param {Object} page
```
Comment (egoist) [inline packages/saber/lib/utils/assetsAttribute.js]: why this?

File: packages/saber/lib/utils/assetsAttribute.js [hunk 2]
```diff
@@ -12,15 +14,16 @@ const MARK_GLOBAL_RE = new RegExp(`"${MARK}([^"]+)"`, 'g')
...
  */
-const prefixAssets = assets => {
-  /** @type {{[key: string]: string}} */
```
Comment (egoist) [inline packages/saber/lib/utils/assetsAttribute.js]: 🤔

**Comment by egoist** [comment]
Published canary release: `saber@0.5.5-canary.170.36919c1.10`
