### PR TITLE
fix: Scroll to anchor not working #213

### LINKED ISSUE #213: Scroll to anchor in `router.scrollBehavior` doesn't work
[Issuehunt badges](https://issuehunt.io/r/saberland/saber/issues/213)

- [x] I confirm that this is an issue rather than a question.

## Bug report

https://github.com/saberland/saber/blob/61992cbcff3ed552aa90e6bff1cf320e1d35da82/packages/saber/vue-renderer/app/router.js#L68-L87

The code attempts to scroll to the anchor if `to.hash` exists and the anchor can be found. But the scroll never happens.

#### Version

0.6.4

#### Steps to reproduce

`about.md`:

```markdown
[Hello](./hello.md#world)
```

`hello.md`:

```markdown
# World

Lorem ipsum...
```

Then click the link in `about.md`.

#### What is expected?

Page scrolled to the title **World**.

#### What is actually happening?

Page scrolled to the top (default behavior).

#### Other relevant information

1. If `to.hash` only contains ASCII characters, the hash before and after escaping are the same. If it contains non-ASCII characters (e.g. CJK characters), escaping the hash will produce a selector matching nothing (assuming header's `id` is generated in standard behavior).

> Possible solution: Use `decodeURIComponent(to.hash)` instead of `window.CSS.escape(to.hash)`

2. Even if the selector is valid, `document.querySelector(hash)` still matches nothing, thus the scroll won't trigger. Chances are page is not loaded at that time.

> Possible solution: Move the codition statement to a hook like `afterPageLoad` or use other methods (can only come up with `setTimeout(condition, 0)`)

- Result of running `saber -v`: cli.js/0.6.4 win32-x64 node-v12.3.1
- Browser version (optional): Google Chrome 76.0.3800.0 (64-bit)
- Is Saber a global or local install? Local
- Which package manager did you use for the install? Yarn
- Does this issue occur when all plugins are disabled? Yes

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $50.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by krmax44**
**Summary**

Fixes #213.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by egoist** [comment]
Let's remove https://github.com/saberland/saber/blob/d778282e6b9a21aeaa80bea115a9f64e70917ea3/website/src/mixins/doc.js#L5 then

**Comment by krmax44** [comment]
I just noticed a couple of changes missing in my PR. I'll push them tomorrow.

File: packages/saber/vue-renderer/app/create-app.js [hunk 1]
```diff
@@ -87,10 +87,10 @@ export default context => {
           delete transition[key]
         }
       })
-      const beforeEnter = listeners['before-enter']
-      listeners['before-enter'] = el => {
+      const afterEnter = listeners['after-enter']
+      listeners['after-enter'] = el => {
         this.$emit('trigger-scroll')
-        beforeEnter && beforeEnter(el)
+        afterEnter && afterEnter(el)
```
Comment (egoist) [inline packages/saber/vue-renderer/app/create-app.js]: What about:

```js
      listeners['before-enter'] = el => {
        this.$nextTick(() => {
          this.$emit('trigger-scroll')
        })
        beforeEnter && beforeEnter(el)
      }
```

**Comment by egoist** [comment]
Another thing needs to fixed: trigger scroll on the initial load, currently we only trigger scroll after route navigation.

**Comment by krmax44** [comment]
Exactly, that change didn't go through. I'll push that later.

File: packages/saber/vue-renderer/app/create-app.js (hunk 1 above)
Comment (egoist) [reply packages/saber/vue-renderer/app/create-app.js]: Might need some help from @pi0 😄

**Comment by krmax44** [comment]
So it works under Firefox but not Chrome :thinking: https://5ced00ce5e1c320008959c62--saber.netlify.com/tutorial/tutorial.html#prerequisites

**Comment by kidonng** [comment]
> So it works under Firefox but not Chrome 🤔 [5ced00ce5e1c320008959c62--saber.netlify.com/tutorial/tutorial.html#prerequisites](https://5ced00ce5e1c320008959c62--saber.netlify.com/tutorial/tutorial.html#prerequisites)

FYI, it works on (old) Edge. So blame Chrome 😢

**Comment by krmax44** [comment]
See https://deploy-preview-214--saber.netlify.com/docs#fn1 nicely scrolls to where it's supposed to go :smile:

File: packages/saber/vue-renderer/app/create-app.js [hunk 2]
```diff
@@ -74,6 +75,15 @@ export default context => {
         transition: null
       }
     },
+    mounted() {
+      this.$router.app.$nextTick(() =>
```
Comment (egoist) [inline packages/saber/vue-renderer/app/create-app.js]: `this.$router.app.$nextTick` seems unnecessary,

File: packages/saber/vue-renderer/app/helpers/scroll-handler.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+function normalizeOffset(obj) {
+  return {
+    x: isNumber(obj.x) ? obj.x : 0,
+    y: isNumber(obj.y) ? obj.y : 0
+  }
+}
+
+function isNumber(v) {
+  return typeof v === 'number'
```
Comment (MarchWorks) [inline packages/saber/vue-renderer/app/helpers/scroll-handler.js]: is there any chance that v is NaN?

Comment (krmax44) [reply packages/saber/vue-renderer/app/helpers/scroll-handler.js]: No, not really, unless a custom `scrollBehavior` function would return something bad. Even if it would be `NaN`, `window.scroll(NaN, NaN)` has the same effect as `window.scroll(0, 0)`, so not really a concern.
