### PR TITLE
fix(link-plugin): remove redundant slash

### LINKED ISSUE #205: Convert relative links to permalinks didn't work
- [x] I confirm that this is an issue rather than a question.

## Bug report

#25 didn't work on Windows 😢.

#### Version

0.6.3

#### Steps to reproduce

Run Saber in [the repo](https://github.com/spekulatius/saber-blog-starter) from #203 (links [fixed](https://github.com/saberland/saber/issues/203#issuecomment-495639774)).

#### What is expected?

Links coverted successfully.

#### What is actually happening?

Both links in pages and posts aren't coverted, output is `/index.md`.

image

#### Other relevant information

- Result of running `saber -v`: cli.js/0.6.3 win32-x64 node-v12.3.1
- Browser version (optional): Chrome 76.0.3800.0
- Is Saber a global or local install? local
- Which package manager did you use for the install? Yarn
- Does this issue occur when all plugins are disabled? Yes

### PR DESCRIPTION
**Pull request by kidonng**
**Summary**

fix #205

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: packages/saber/lib/markdown/link-plugin.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ module.exports = function(md) {
             path.dirname(env.filePath),
             matched[1]
           )
-          if (absolutePath.includes(`${env.pagesDir}/`)) {
+          if (absolutePath.includes(env.pagesDir)) {
```
Comment (egoist) [inline packages/saber/lib/markdown/link-plugin.js]:
```suggestion
          if (absolutePath.startsWith(env.pagesDir)) {
```
